INFO     utils.utils:conftest.py:33 Connecting to WebDriver on http://127.0.0.1:4723 for device 'Galaxy S24 Ultra'
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001955F90A310>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001955F90A1F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001955F9365B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session
ERROR    utils.utils:conftest.py:36 Failed to connect to WebDriver: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001955F9368B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))